/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.pkg8p2_equipo.pkg12;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alema
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_DanielEliminar = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        button_agregarSerVivomod1 = new javax.swing.JButton();
        button_volverSerVivomod1 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        combobox_modificarpersona1 = new javax.swing.JComboBox<>();
        frame_DanielModificar = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textfield_SerVivoNombremod = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        formattedfield_SerVivoIDmod = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        spinner_SerVivoPodermod = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        formattedfield_SerVivoAniomod = new javax.swing.JFormattedTextField();
        combobox_SerVivoUniversomod = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        combobox_SerVivoRazamod = new javax.swing.JComboBox<>();
        button_agregarSerVivomod = new javax.swing.JButton();
        button_volverSerVivomod = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        combobox_modificarpersona = new javax.swing.JComboBox<>();
        frame_DanielAgregar = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textfield_SerVivoNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        formattedfield_SerVivoID = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        spinner_SerVivoPoder = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        formattedfield_SerVivoAnio = new javax.swing.JFormattedTextField();
        combobox_SerVivoUniverso = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        combobox_SerVivoRaza = new javax.swing.JComboBox<>();
        button_agregarSerVivo = new javax.swing.JButton();
        button_modificarSerVivo = new javax.swing.JButton();
        frame_DanielSeres = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        button_SerVivoAgregar = new javax.swing.JButton();
        button_SerVivoModificar = new javax.swing.JButton();
        button_SerVivoEliminar = new javax.swing.JButton();
        button_SerVivoRegresar = new javax.swing.JButton();
        frame_LisaUniverso = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        JB_AnadirUni = new javax.swing.JButton();
        JB_ModUniverso = new javax.swing.JButton();
        JB_EliminarUni = new javax.swing.JButton();
        JB_AtrasCrudUni = new javax.swing.JButton();
        frame_LisaAgregar = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TF_NombreAgregarUni = new javax.swing.JTextField();
        JB_AgregarfinalUni = new javax.swing.JButton();
        JB_AtrasAgregarUni = new javax.swing.JButton();
        frame_LisaModUniverso = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        TF_NombreModificarUni = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        CB_ModificarUni = new javax.swing.JComboBox<>();
        JB_AtrasModUni = new javax.swing.JButton();
        JB_ModificarUniFinal = new javax.swing.JButton();
        JF_EliminarUni = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Eliminar = new javax.swing.JTable();
        JB_EliminarFinalUni = new javax.swing.JButton();
        JB_AtrasEliminarUni = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JB_Servivo = new javax.swing.JButton();
        JB_Universo = new javax.swing.JButton();
        JB_Guardar = new javax.swing.JButton();
        JB_Salir = new javax.swing.JButton();

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel28.setText("Eliminar un Ser Vivo ");

        button_agregarSerVivomod1.setBackground(new java.awt.Color(255, 255, 204));
        button_agregarSerVivomod1.setText("OK");

        button_volverSerVivomod1.setBackground(new java.awt.Color(255, 255, 204));
        button_volverSerVivomod1.setText("VOLVER");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setText("Ser a eliminar :");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(button_volverSerVivomod1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_agregarSerVivomod1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combobox_modificarpersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(combobox_modificarpersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_agregarSerVivomod1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_volverSerVivomod1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout frame_DanielEliminarLayout = new javax.swing.GroupLayout(frame_DanielEliminar.getContentPane());
        frame_DanielEliminar.getContentPane().setLayout(frame_DanielEliminarLayout);
        frame_DanielEliminarLayout.setHorizontalGroup(
            frame_DanielEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_DanielEliminarLayout.setVerticalGroup(
            frame_DanielEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("Modificar un Ser Vivo ");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Nombre");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("ID");

        try {
            formattedfield_SerVivoIDmod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Poder");

        spinner_SerVivoPodermod.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Año");

        try {
            formattedfield_SerVivoAniomod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Universo");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Raza");

        button_agregarSerVivomod.setBackground(new java.awt.Color(255, 255, 204));
        button_agregarSerVivomod.setText("OK");

        button_volverSerVivomod.setBackground(new java.awt.Color(255, 255, 204));
        button_volverSerVivomod.setText("VOLVER");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Ser a modificar :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(combobox_SerVivoUniversomod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textfield_SerVivoNombremod)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(formattedfield_SerVivoIDmod, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedfield_SerVivoAniomod)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_SerVivoRazamod, 0, 175, Short.MAX_VALUE)
                            .addComponent(spinner_SerVivoPodermod))
                        .addGap(175, 175, 175))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(button_volverSerVivomod, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_agregarSerVivomod, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combobox_modificarpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 216, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(combobox_modificarpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_SerVivoNombremod, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner_SerVivoPodermod, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formattedfield_SerVivoIDmod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formattedfield_SerVivoAniomod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_SerVivoUniversomod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_SerVivoRazamod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_agregarSerVivomod, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_volverSerVivomod, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout frame_DanielModificarLayout = new javax.swing.GroupLayout(frame_DanielModificar.getContentPane());
        frame_DanielModificar.getContentPane().setLayout(frame_DanielModificarLayout);
        frame_DanielModificarLayout.setHorizontalGroup(
            frame_DanielModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_DanielModificarLayout.setVerticalGroup(
            frame_DanielModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Crear un Ser Vivo ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ID");

        try {
            formattedfield_SerVivoID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Poder");

        spinner_SerVivoPoder.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Año");

        try {
            formattedfield_SerVivoAnio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Universo");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Raza");

        button_agregarSerVivo.setBackground(new java.awt.Color(255, 255, 204));
        button_agregarSerVivo.setText("OK");
        button_agregarSerVivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_agregarSerVivoMouseClicked(evt);
            }
        });

        button_modificarSerVivo.setBackground(new java.awt.Color(255, 255, 204));
        button_modificarSerVivo.setText("VOLVER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(button_modificarSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_agregarSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(combobox_SerVivoUniverso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textfield_SerVivoNombre)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(formattedfield_SerVivoID, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formattedfield_SerVivoAnio)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_SerVivoRaza, 0, 175, Short.MAX_VALUE)
                            .addComponent(spinner_SerVivoPoder))
                        .addGap(175, 175, 175))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_SerVivoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner_SerVivoPoder, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formattedfield_SerVivoID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formattedfield_SerVivoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_SerVivoUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_SerVivoRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_agregarSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_modificarSerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout frame_DanielAgregarLayout = new javax.swing.GroupLayout(frame_DanielAgregar.getContentPane());
        frame_DanielAgregar.getContentPane().setLayout(frame_DanielAgregarLayout);
        frame_DanielAgregarLayout.setHorizontalGroup(
            frame_DanielAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_DanielAgregarLayout.setVerticalGroup(
            frame_DanielAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("CRUD Seres Vivientes");

        button_SerVivoAgregar.setBackground(new java.awt.Color(255, 255, 204));
        button_SerVivoAgregar.setText("Agregar Ser Vivo");
        button_SerVivoAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_SerVivoAgregarMouseClicked(evt);
            }
        });

        button_SerVivoModificar.setBackground(new java.awt.Color(255, 255, 204));
        button_SerVivoModificar.setText("Modificar Ser Vivo");

        button_SerVivoEliminar.setBackground(new java.awt.Color(255, 255, 204));
        button_SerVivoEliminar.setText("Eliminar Ser Vivo");

        button_SerVivoRegresar.setBackground(new java.awt.Color(255, 255, 204));
        button_SerVivoRegresar.setText("Volver");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_SerVivoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_SerVivoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_SerVivoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_SerVivoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(167, 167, 167))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(button_SerVivoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(button_SerVivoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(button_SerVivoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(button_SerVivoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frame_DanielSeresLayout = new javax.swing.GroupLayout(frame_DanielSeres.getContentPane());
        frame_DanielSeres.getContentPane().setLayout(frame_DanielSeresLayout);
        frame_DanielSeresLayout.setHorizontalGroup(
            frame_DanielSeresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_DanielSeresLayout.setVerticalGroup(
            frame_DanielSeresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        jLabel8.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel8.setText("CRUD Universo");

        JB_AnadirUni.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        JB_AnadirUni.setText("Agregar");
        JB_AnadirUni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AnadirUniMouseClicked(evt);
            }
        });

        JB_ModUniverso.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        JB_ModUniverso.setText("Modificar");
        JB_ModUniverso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_ModUniversoMouseClicked(evt);
            }
        });

        JB_EliminarUni.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        JB_EliminarUni.setText("Eliminar");
        JB_EliminarUni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_EliminarUniMouseClicked(evt);
            }
        });

        JB_AtrasCrudUni.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        JB_AtrasCrudUni.setText("Atras");
        JB_AtrasCrudUni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AtrasCrudUniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JB_AtrasCrudUni, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_EliminarUni, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_ModUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_AnadirUni, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(JB_AnadirUni, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(JB_ModUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_EliminarUni, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_AtrasCrudUni, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frame_LisaUniversoLayout = new javax.swing.GroupLayout(frame_LisaUniverso.getContentPane());
        frame_LisaUniverso.getContentPane().setLayout(frame_LisaUniversoLayout);
        frame_LisaUniversoLayout.setHorizontalGroup(
            frame_LisaUniversoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_LisaUniversoLayout.setVerticalGroup(
            frame_LisaUniversoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));

        jLabel9.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel9.setText("Nombre:");

        jLabel10.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel10.setText("Agregar Universo");

        TF_NombreAgregarUni.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N

        JB_AgregarfinalUni.setText("Agregar");
        JB_AgregarfinalUni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarfinalUniMouseClicked(evt);
            }
        });

        JB_AtrasAgregarUni.setText("Atras");
        JB_AtrasAgregarUni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AtrasAgregarUniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TF_NombreAgregarUni, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(JB_AtrasAgregarUni)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JB_AgregarfinalUni))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_NombreAgregarUni, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_AgregarfinalUni)
                    .addComponent(JB_AtrasAgregarUni))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frame_LisaAgregarLayout = new javax.swing.GroupLayout(frame_LisaAgregar.getContentPane());
        frame_LisaAgregar.getContentPane().setLayout(frame_LisaAgregarLayout);
        frame_LisaAgregarLayout.setHorizontalGroup(
            frame_LisaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_LisaAgregarLayout.setVerticalGroup(
            frame_LisaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_LisaAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(520, 440));

        jLabel21.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel21.setText("Modificar Universo");

        TF_NombreModificarUni.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel22.setText("Escoja el Universo");

        jLabel23.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel23.setText("Nombre");

        CB_ModificarUni.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_ModificarUniItemStateChanged(evt);
            }
        });

        JB_AtrasModUni.setText("Atras");
        JB_AtrasModUni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AtrasModUniMouseClicked(evt);
            }
        });

        JB_ModificarUniFinal.setText("Modificar");
        JB_ModificarUniFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_ModificarUniFinalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addComponent(CB_ModificarUni, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(jLabel21))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(386, 386, 386)
                            .addComponent(JB_ModificarUniFinal)))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JB_AtrasModUni)
                        .addComponent(TF_NombreModificarUni, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(390, 390, 390))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(12, 12, 12)
                .addComponent(CB_ModificarUni, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_NombreModificarUni, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_ModificarUniFinal)
                    .addComponent(JB_AtrasModUni))
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout frame_LisaModUniversoLayout = new javax.swing.GroupLayout(frame_LisaModUniverso.getContentPane());
        frame_LisaModUniverso.getContentPane().setLayout(frame_LisaModUniversoLayout);
        frame_LisaModUniversoLayout.setHorizontalGroup(
            frame_LisaModUniversoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        frame_LisaModUniversoLayout.setVerticalGroup(
            frame_LisaModUniversoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(102, 153, 255));

        jLabel24.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel24.setText("Eliminar Universo");

        JT_Eliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane1.setViewportView(JT_Eliminar);

        JB_EliminarFinalUni.setText("Eliminar");
        JB_EliminarFinalUni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_EliminarFinalUniMouseClicked(evt);
            }
        });

        JB_AtrasEliminarUni.setText("Atras");
        JB_AtrasEliminarUni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AtrasEliminarUniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(JB_AtrasEliminarUni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_EliminarFinalUni)))
                .addGap(45, 45, 45))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_EliminarFinalUni)
                    .addComponent(JB_AtrasEliminarUni))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JF_EliminarUniLayout = new javax.swing.GroupLayout(JF_EliminarUni.getContentPane());
        JF_EliminarUni.getContentPane().setLayout(JF_EliminarUniLayout);
        JF_EliminarUniLayout.setHorizontalGroup(
            JF_EliminarUniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JF_EliminarUniLayout.setVerticalGroup(
            JF_EliminarUniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 0));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Bienvenido Ser Vivo");

        JB_Servivo.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        JB_Servivo.setText("Ser Vivo");
        JB_Servivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_ServivoMouseClicked(evt);
            }
        });

        JB_Universo.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        JB_Universo.setText("Universo");
        JB_Universo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_UniversoMouseClicked(evt);
            }
        });

        JB_Guardar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        JB_Guardar.setText("Guardar");

        JB_Salir.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        JB_Salir.setText("Salir");
        JB_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_SalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JB_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_Guardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_Universo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(JB_Servivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(196, 196, 196))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_Servivo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_Universo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JB_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_JB_SalirMouseClicked

    private void JB_ServivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ServivoMouseClicked
        this.setVisible(false);
        frame_DanielSeres.setVisible(true);
        frame_DanielSeres.pack();
        frame_DanielSeres.setLocationRelativeTo(this);
    }//GEN-LAST:event_JB_ServivoMouseClicked

    private void JB_UniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_UniversoMouseClicked
        this.setVisible(false);
        frame_LisaUniverso.setVisible(true);
        frame_LisaUniverso.pack();
        frame_LisaUniverso.setLocationRelativeTo(this);
    }//GEN-LAST:event_JB_UniversoMouseClicked

    private void JB_AgregarfinalUniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarfinalUniMouseClicked
        try {
            u = new Universo(TF_NombreAgregarUni.getText());
            uni.add(u);
            TF_NombreAgregarUni.setText("");
            JOptionPane.showMessageDialog(this, "Universo Agregado Exitosamente");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JB_AgregarfinalUniMouseClicked

    private void button_SerVivoAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_SerVivoAgregarMouseClicked
        frame_DanielSeres.setVisible(false);
        frame_DanielAgregar.setVisible(true);
        frame_DanielAgregar.pack();
        frame_DanielAgregar.setLocationRelativeTo(this);
    }//GEN-LAST:event_button_SerVivoAgregarMouseClicked

    private void JB_AnadirUniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AnadirUniMouseClicked
        frame_LisaUniverso.setVisible(false);
        frame_LisaAgregar.setVisible(true);
        frame_LisaAgregar.pack();
        frame_LisaAgregar.setLocationRelativeTo(this);

    }//GEN-LAST:event_JB_AnadirUniMouseClicked

    private void JB_ModUniversoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ModUniversoMouseClicked
        frame_LisaUniverso.setVisible(false);
        
        frame_LisaModUniverso.pack();
        frame_LisaModUniverso.setLocationRelativeTo(this);
        frame_LisaModUniverso.setVisible(true);
        llenarcomboUniverso();
    }//GEN-LAST:event_JB_ModUniversoMouseClicked

    private void JB_AtrasAgregarUniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AtrasAgregarUniMouseClicked
        frame_LisaAgregar.setVisible(false);
        frame_LisaUniverso.setVisible(true);
        frame_LisaUniverso.pack();
        frame_LisaUniverso.setLocationRelativeTo(this);
    }//GEN-LAST:event_JB_AtrasAgregarUniMouseClicked

    private void JB_AtrasModUniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AtrasModUniMouseClicked
        frame_LisaModUniverso.setVisible(false);
        frame_LisaUniverso.setVisible(true);
        frame_LisaUniverso.pack();
        frame_LisaUniverso.setLocationRelativeTo(this);
    }//GEN-LAST:event_JB_AtrasModUniMouseClicked

    private void JB_ModificarUniFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ModificarUniFinalMouseClicked
        try {
            for (int i = 0; i < uni.size(); i++) {
                u = uni.get(i);
                if (u.getNombre().equals(CB_ModificarUni.getSelectedItem().toString())) {
                    u.setNombre(TF_NombreModificarUni.getText());
                    JOptionPane.showMessageDialog(this, "Universo Modificado Exitosamente");
                }
            }
            System.out.println(uni);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_JB_ModificarUniFinalMouseClicked

    private void CB_ModificarUniItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_ModificarUniItemStateChanged
        for (Universo u : uni) {
            if (CB_ModificarUni.getSelectedItem().equals(u.toString())) {
                TF_NombreModificarUni.setText(CB_ModificarUni.getSelectedItem().toString());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_ModificarUniItemStateChanged

    private void JB_EliminarUniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EliminarUniMouseClicked
        frame_LisaUniverso.setVisible(false);
        
        JF_EliminarUni.pack();
        JF_EliminarUni.setLocationRelativeTo(this);
        JF_EliminarUni.setVisible(true);
        listarTabla();
    }//GEN-LAST:event_JB_EliminarUniMouseClicked

    private void JB_AtrasCrudUniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AtrasCrudUniMouseClicked
        frame_LisaUniverso.setVisible(false);
        this.setVisible(true);
 
    }//GEN-LAST:event_JB_AtrasCrudUniMouseClicked

    private void JB_AtrasEliminarUniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AtrasEliminarUniMouseClicked
       JF_EliminarUni.setVisible(false);
        frame_LisaUniverso.setVisible(true);
        frame_LisaUniverso.pack();
        frame_LisaUniverso.setLocationRelativeTo(this);
    }//GEN-LAST:event_JB_AtrasEliminarUniMouseClicked

    private void JB_EliminarFinalUniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EliminarFinalUniMouseClicked
              if (JT_Eliminar.getSelectedRow() >= 0) {
            int r = JOptionPane.showConfirmDialog(JT_Eliminar, "Desea elimnar Universo????", "Eliminar Universo", YES_NO_OPTION);
            if (r == 0) {
                uni.remove(JT_Eliminar.getSelectedRow());
                listarTabla();
                JOptionPane.showMessageDialog(this, "Universo Eliminado exitosamente");

            }

        }
    }//GEN-LAST:event_JB_EliminarFinalUniMouseClicked

    private void button_agregarSerVivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_agregarSerVivoMouseClicked
       
    }//GEN-LAST:event_button_agregarSerVivoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void llenarcomboUniverso() {
        CB_ModificarUni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        for (Universo t : uni) {
            DefaultComboBoxModel modelo
                    = (DefaultComboBoxModel) CB_ModificarUni.getModel();
            modelo.addElement(t.getNombre());
            CB_ModificarUni.setModel(modelo);

        }
    }
    private void listarTabla() {
        try {

            //limpiar tabla
            JT_Eliminar.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{
                "Nombre"}));

            // TODO add your handling code here:
            for (Universo t : uni) {
                    Object[] row = {t.getNombre()};
                    DefaultTableModel modelo = (DefaultTableModel) JT_Eliminar.getModel();
                    modelo.addRow(row);
                    JT_Eliminar.setModel(modelo);
                
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_ModificarUni;
    private javax.swing.JButton JB_AgregarfinalUni;
    private javax.swing.JButton JB_AnadirUni;
    private javax.swing.JButton JB_AtrasAgregarUni;
    private javax.swing.JButton JB_AtrasCrudUni;
    private javax.swing.JButton JB_AtrasEliminarUni;
    private javax.swing.JButton JB_AtrasModUni;
    private javax.swing.JButton JB_EliminarFinalUni;
    private javax.swing.JButton JB_EliminarUni;
    private javax.swing.JButton JB_Guardar;
    private javax.swing.JButton JB_ModUniverso;
    private javax.swing.JButton JB_ModificarUniFinal;
    private javax.swing.JButton JB_Salir;
    private javax.swing.JButton JB_Servivo;
    private javax.swing.JButton JB_Universo;
    private javax.swing.JFrame JF_EliminarUni;
    private javax.swing.JTable JT_Eliminar;
    private javax.swing.JTextField TF_NombreAgregarUni;
    private javax.swing.JTextField TF_NombreModificarUni;
    private javax.swing.JButton button_SerVivoAgregar;
    private javax.swing.JButton button_SerVivoEliminar;
    private javax.swing.JButton button_SerVivoModificar;
    private javax.swing.JButton button_SerVivoRegresar;
    private javax.swing.JButton button_agregarSerVivo;
    private javax.swing.JButton button_agregarSerVivomod;
    private javax.swing.JButton button_agregarSerVivomod1;
    private javax.swing.JButton button_modificarSerVivo;
    private javax.swing.JButton button_volverSerVivomod;
    private javax.swing.JButton button_volverSerVivomod1;
    private javax.swing.JComboBox<String> combobox_SerVivoRaza;
    private javax.swing.JComboBox<String> combobox_SerVivoRazamod;
    private javax.swing.JComboBox<String> combobox_SerVivoUniverso;
    private javax.swing.JComboBox<String> combobox_SerVivoUniversomod;
    private javax.swing.JComboBox<String> combobox_modificarpersona;
    private javax.swing.JComboBox<String> combobox_modificarpersona1;
    private javax.swing.JFormattedTextField formattedfield_SerVivoAnio;
    private javax.swing.JFormattedTextField formattedfield_SerVivoAniomod;
    private javax.swing.JFormattedTextField formattedfield_SerVivoID;
    private javax.swing.JFormattedTextField formattedfield_SerVivoIDmod;
    private javax.swing.JFrame frame_DanielAgregar;
    private javax.swing.JFrame frame_DanielEliminar;
    private javax.swing.JFrame frame_DanielModificar;
    private javax.swing.JFrame frame_DanielSeres;
    private javax.swing.JFrame frame_LisaAgregar;
    private javax.swing.JFrame frame_LisaModUniverso;
    private javax.swing.JFrame frame_LisaUniverso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinner_SerVivoPoder;
    private javax.swing.JSpinner spinner_SerVivoPodermod;
    private javax.swing.JTextField textfield_SerVivoNombre;
    private javax.swing.JTextField textfield_SerVivoNombremod;
    // End of variables declaration//GEN-END:variables
Universo u;
    ArrayList<Universo> uni = new ArrayList();
}
